

INSERT INTO usuarios (USU_NOMBRE, USU_USUARIOS, USU_CONTRASENA,
USU_ID_ALTA, USU_FECHA_ALTA)
VALUES ('Admin', 1, 'Admin', 1, now());

INSERT INTO tipos_porcion(TPO_NOMBRE, 
TPO_USU_ID_ALTA, TPO_FECHA_ALTA,
TPO_USU_ID_MODIFICACION, TPO_FECHA_MODIFICACION)
VALUES ('gramos',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);



INSERT INTO ingredientes(ING_NOMBRE, 
ING_USU_ID_ALTA, ING_FECHA_ALTA,
ING_USU_ID_MODIFICACION, ING_FECHA_MODIFICACION
)
VALUES ('Leche entera pasteurizada',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO ingredientes(ING_NOMBRE, 
ING_USU_ID_ALTA, ING_FECHA_ALTA,
ING_USU_ID_MODIFICACION, ING_FECHA_MODIFICACION)
VALUES ('Azúcar',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now());

INSERT INTO ingredientes(ING_NOMBRE, 
ING_USU_ID_ALTA, ING_FECHA_ALTA,
ING_USU_ID_MODIFICACION, ING_FECHA_MODIFICACION)
VALUES ('Glucosa',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now());

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Carbohidratos', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Proteínas', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Grasas totales', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Grasas saturadas', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Grasas trans', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Fibra', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Sodio', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO productos(PRO_NOMBRE, PRO_PORCION, PRO_TPO_ID,
PRO_USU_ID_ALTA, PRO_FECHA_ALTA,
PRO_USU_ID_MODIFICACION, PRO_FECHA_MODIFICACION
)
VALUES ('Dulce de leche repostero Los quebrachitos', 20, (select TPO_ID from TIPOS_PORCION where TPO_NOMBRE='gramos'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO ingredientes_x_productos(IPR_PRO_ID, IPR_ING_ID,
IPR_USU_ID_ALTA, IPR_FECHA_ALTA,
IPR_USU_ID_MODIFICACION, IPR_FECHA_MODIFICACION
)
VALUES( (select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select ING_ID from ingredientes where ING_NOMBRE='Leche entera pasteurizada'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO ingredientes_x_productos(IPR_PRO_ID, IPR_ING_ID,
IPR_USU_ID_ALTA, IPR_FECHA_ALTA,
IPR_USU_ID_MODIFICACION, IPR_FECHA_MODIFICACION
)
VALUES( (select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select ING_ID from ingredientes where ING_NOMBRE='Azúcar'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO ingredientes_x_productos(IPR_PRO_ID, IPR_ING_ID,
IPR_USU_ID_ALTA, IPR_FECHA_ALTA,
IPR_USU_ID_MODIFICACION, IPR_FECHA_MODIFICACION
)
VALUES( (select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select ING_ID from ingredientes where ING_NOMBRE='Glucosa'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Carbohidratos'),
12,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Proteínas'),
1.1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Grasas totales'),
1.1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Grasas saturadas'),
0.7,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Grasas trans'),
0,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Fibra'),
0,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Sodio'),
0.021,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);




INSERT INTO tipos_alerta(tal_nombre, tal_color, tal_forma,
tal_USU_ID_ALTA, tal_FECHA_ALTA,
tal_USU_ID_MODIFICACION, tal_FECHA_MODIFICACION
)
values ('Sello de advertencia', '000000', 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO alertas(ale_nombre, ale_leyenda, ale_tal_id,
ale_USU_ID_ALTA, ale_FECHA_ALTA,
ale_USU_ID_MODIFICACION, ale_FECHA_MODIFICACION
)
values ('Exceso en sodio', 'Exceso en sodio', (select tal_id from tipos_alerta where tal_nombre='Sello de advertencia'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO alertas_x_nutriente(anu_ale_id, anu_nut_id, anu_valor_critico,
anu_USU_ID_ALTA, anu_FECHA_ALTA,
anu_USU_ID_MODIFICACION, anu_FECHA_MODIFICACION
)
values ((select ale_id from alertas where ale_nombre='Exceso en sodio'), (select nut_id from nutrientes where nut_nombre='Sodio'), 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);



INSERT INTO alertas(ale_nombre, ale_leyenda, ale_tal_id,
ale_USU_ID_ALTA, ale_FECHA_ALTA,
ale_USU_ID_MODIFICACION, ale_FECHA_MODIFICACION
)
values ('Exceso en grasas saturadas', 'Exceso en grasas saturadas', (select tal_id from tipos_alerta where tal_nombre='Sello de advertencia'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);



INSERT INTO alertas_x_nutriente(anu_ale_id, anu_nut_id, anu_valor_critico,
anu_USU_ID_ALTA, anu_FECHA_ALTA,
anu_USU_ID_MODIFICACION, anu_FECHA_MODIFICACION
)
values ((select ale_id from alertas where ale_nombre='Exceso en grasas saturadas'), (select nut_id from nutrientes where nut_nombre='Grasas saturadas'), 10,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);
