

INSERT INTO usuarios (USU_NOMBRE, USU_USUARIOS, USU_CONTRASENA,
USU_ID_ALTA, USU_FECHA_ALTA)
VALUES ('Admin', 1, 'Admin', 1, now());

INSERT INTO tipos_alerta(TAL_COLOR, TAL_FORMA, 
TAL_USU_ID_ALTA, TAL_FECHA_ALTA, TAL_USU_ID_MODIFICACION, TAL_FECHA_MODIFICACION)
VALUES ('000000', 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);



INSERT INTO tipos_porcion(TPO_NOMBRE, 
TPO_USU_ID_ALTA, TPO_FECHA_ALTA,
TPO_USU_ID_MODIFICACION, TPO_FECHA_MODIFICACION)
VALUES ('gramos',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);



INSERT INTO ingredientes(ING_NOMBRE, 
ING_USU_ID_ALTA, ING_FECHA_ALTA,
ING_USU_ID_MODIFICACION, ING_FECHA_MODIFICACION
)
VALUES ('Leche entera pasteurizada',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO ingredientes(ING_NOMBRE, 
ING_USU_ID_ALTA, ING_FECHA_ALTA,
ING_USU_ID_MODIFICACION, ING_FECHA_MODIFICACION)
VALUES ('Azúcar',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now());

INSERT INTO ingredientes(ING_NOMBRE, 
ING_USU_ID_ALTA, ING_FECHA_ALTA,
ING_USU_ID_MODIFICACION, ING_FECHA_MODIFICACION)
VALUES ('Glucosa',
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now());

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Carbohidratos', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Proteínas', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Grasas totales', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Grasas saturadas', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Grasas trans', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Fibra', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes(NUT_NOMBRE, NUT_ES_OPCIONAL, NUT_ES_CRITICO,
NUT_USU_ID_ALTA, NUT_FECHA_ALTA,
NUT_USU_ID_MODIFICACION, NUT_FECHA_MODIFICACION)
VALUES
('Sodio', 0, 1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO productos(PRO_NOMBRE, PRO_PORCION, PRO_TPO_ID,
PRO_USU_ID_ALTA, PRO_FECHA_ALTA,
PRO_USU_ID_MODIFICACION, PRO_FECHA_MODIFICACION
)
VALUES ('Dulce de leche repostero Los quebrachitos', 20, (select TPO_ID from TIPOS_PORCION where TPO_NOMBRE='gramos'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO ingredientes_x_productos(IPR_PRO_ID, IPR_ING_ID,
IPR_USU_ID_ALTA, IPR_FECHA_ALTA,
IPR_USU_ID_MODIFICACION, IPR_FECHA_MODIFICACION
)
VALUES( (select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select ING_ID from ingredientes where ING_NOMBRE='Leche entera pasteurizada'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO ingredientes_x_productos(IPR_PRO_ID, IPR_ING_ID,
IPR_USU_ID_ALTA, IPR_FECHA_ALTA,
IPR_USU_ID_MODIFICACION, IPR_FECHA_MODIFICACION
)
VALUES( (select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select ING_ID from ingredientes where ING_NOMBRE='Azúcar'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO ingredientes_x_productos(IPR_PRO_ID, IPR_ING_ID,
IPR_USU_ID_ALTA, IPR_FECHA_ALTA,
IPR_USU_ID_MODIFICACION, IPR_FECHA_MODIFICACION
)
VALUES( (select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select ING_ID from ingredientes where ING_NOMBRE='Glucosa'),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Carbohidratos'),
12,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Proteínas'),
1.1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Grasas totales'),
1.1,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Grasas saturadas'),
0.7,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);

INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Grasas trans'),
0,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Fibra'),
0,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);


INSERT INTO nutrientes_x_productos(NPR_PRO_ID, NPR_NUT_ID, NPR_CANTIDAD_POR_PORCION,
NPR_USU_ID_ALTA, NPR_FECHA_ALTA,
NPR_USU_ID_MODIFICACION, NPR_FECHA_MODIFICACION)
VALUES(
(select PRO_ID from productos where PRO_NOMBRE='Dulce de leche repostero Los quebrachitos'),
(select NUT_ID from nutrientes where NUT_NOMBRE='Sodio'),
0.021,
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now(),
(SELECT USU_ID FROM USUARIOS WHERE USU_NOMBRE='Admin'), now()
);